import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import remappingImport from "@ampproject/remapping";
import { Codes } from "@nola-lang/ast";
import { companionSourceCandidates, companionSpecifierFor, compileCompanion, compileNola } from "@nola-lang/compiler";
import {
  bundleSelfConfiguringConfig,
  findProjectRoot,
  loadBuildOptions,
  loadCompilerOptions,
} from "@nola-lang/node-loader";
import { transformSync } from "esbuild";
import { printDiagnostics } from "./diag.js";
import type { LoweredEntry } from "./tshost.js";
import { emitDeclarationTexts } from "./tshost-declarations.js";
import { walkProject } from "./walk.js";

type SourceMapish = { toString(): string; sources: string[] };
type Remapping = (input: unknown, loader: (sourcefile: string) => unknown, options?: boolean) => SourceMapish;
const remapping = remappingImport as unknown as Remapping;

export interface BuildResult {
  written: string[];
  errors: string[];
}

/** First line of the emitted config bundle; the overwrite guard keys on it. */
const CONFIG_BUNDLE_MARKER = "// generated by nola build — self-configuring Nola config bundle";

export async function cmdBuild(dirArg = ".", outArg = "dist"): Promise<BuildResult> {
  const dir = resolve(dirArg);
  const out = resolve(outArg);
  const sourceRoot = findProjectRoot(dir);
  const { underivableContextType } = await loadCompilerOptions(dir);
  const { target, configPath } = await loadBuildOptions(dir);
  const wireConfig = target === "app" && configPath !== null;
  const configOutPath = join(out, "nola.config.js");
  const written: string[] = [];
  const errors: string[] = [];
  const lowered: LoweredEntry[] = [];
  const metas: string[][] = [];

  const { tsi, reserved } = await walkProject(dir);
  for (const file of reserved) {
    errors.push(
      `${file} ${Codes.ReservedCompanionPath}: the *.nola.* filename namespace is reserved for generated companion modules — rename this file`,
    );
  }
  if (errors.length > 0) return { written, errors };

  // App builds ship the config: bundle nola.config.ts (relative imports
  // inlined, packages external) with a self-configuring wrapper, emitted
  // first so a bad config fails the build before any compilation.
  if (wireConfig) {
    if (existsSync(configOutPath) && !(await readFile(configOutPath, "utf8")).startsWith(CONFIG_BUNDLE_MARKER)) {
      errors.push(
        `${configOutPath}: exists and was not generated by nola build — refusing to overwrite. Is another toolchain compiling nola.config.ts into --out?`,
      );
      return { written, errors };
    }
    try {
      const bundled = await bundleSelfConfiguringConfig(configPath as string);
      await mkdir(out, { recursive: true });
      await writeFile(configOutPath, `${CONFIG_BUNDLE_MARKER}\n${bundled}`);
      written.push(configOutPath);
    } catch (err) {
      errors.push(err instanceof Error ? err.message : String(err));
      return { written, errors };
    }
  }

  for (const file of tsi) {
    const source = await readFile(file, "utf8");
    const result = compileNola(source, file, { sourceRoot, underivableContextType });
    if (result.diagnostics.length > 0) {
      errors.push(printDiagnostics(result.diagnostics, () => source));
      continue;
    }
    lowered.push({ file, loweredCode: result.code });
    metas.push(result.meta.companions);

    // The wiring import is appended to the TRANSFORM INPUT only — the
    // declarations pass reuses result.code and must never see it. EOF keeps
    // positions intact; the appended line has no counterpart in result.map,
    // so it stays unmapped after the merge.
    const outPath = `${join(out, relative(dir, file))}.js`;
    let emitCode = result.code;
    if (wireConfig) {
      const rel = relative(dirname(outPath), configOutPath).replace(/\\/g, "/");
      emitCode = `${result.code}\nimport ${JSON.stringify(rel.startsWith(".") ? rel : `./${rel}`)};\n`;
    }
    const js = transformSync(emitCode, { loader: "ts", format: "esm", sourcemap: "external", sourcefile: file });
    let consumed = false;
    const merged = remapping(js.map, () => {
      if (consumed) return null;
      consumed = true;
      return result.map;
    });
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, `${js.code}\n//# sourceMappingURL=${basename(outPath)}.map\n`);
    await writeFile(`${outPath}.map`, merged.toString());
    written.push(outPath, `${outPath}.map`);
  }

  // Companion worklist: every reachable type source gets one real module in
  // dist, named by the same forward transform the lowered imports use — so
  // production output needs no loader at all.
  const emittedCompanions = new Set<string>();
  const companionQueue = lowered.flatMap((entry, i) =>
    (metas[i] ?? []).map((specifier) => ({ importer: entry.file, specifier })),
  );
  while (companionQueue.length > 0) {
    const { importer, specifier } = companionQueue.shift() as { importer: string; specifier: string };
    const src = companionSourceCandidates(specifier)
      .map((c) => resolve(dirname(importer), c))
      .find((p) => existsSync(p));
    if (!src) {
      errors.push(`${importer} ${Codes.CompanionUnavailable}: cannot locate the type source for "${specifier}"`);
      continue;
    }
    if (emittedCompanions.has(src)) continue;
    emittedCompanions.add(src);
    const companion = compileCompanion(await readFile(src, "utf8"), src, { sourceRoot });
    if (companion.code === "" || companion.diagnostics.length > 0) {
      errors.push(printDiagnostics(companion.diagnostics, () => ""));
      continue;
    }
    const js = transformSync(companion.code, { loader: "ts", format: "esm" });
    const outName = companionSpecifierFor(basename(src));
    const outPath = join(out, relative(dir, join(dirname(src), outName)));
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, js.code);
    written.push(outPath);
    companionQueue.push(...companion.companions.map((c) => ({ importer: src, specifier: c })));
  }

  const texts = await emitDeclarationTexts(lowered, metas, sourceRoot, dir);
  for (const [file, declarationText] of texts) {
    // Next to the built .js in --out (report.tsi.js + report.tsi.d.ts pair
    // under NodeNext), NEVER adjacent to the source: the editor serves
    // .tsi virtually, and an on-disk declaration would only shadow it.
    const dtsPath = `${join(out, relative(dir, file))}.d.ts`;
    await mkdir(dirname(dtsPath), { recursive: true });
    await writeFile(dtsPath, declarationText);
    written.push(dtsPath);
  }
  return { written, errors };
}
