import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";
import remappingImport from "@ampproject/remapping";
import {
  bundleSelfConfiguringConfig,
  findProjectRoot,
  loadBuildOptions,
  loadCompilerOptions,
} from "@nola-lang/node-loader";
import { transformSync } from "esbuild";
import { createProjectDeriver, type ProjectDeriver } from "./derive.js";
import { printDiagnostics } from "./diag.js";
import type { LoweredEntry } from "./tshost.js";
import { emitDeclarationTexts } from "./tshost-declarations.js";
import { danglingViewErrors } from "./views.js";
import { siblingWarning, walkProject } from "./walk.js";

type SourceMapish = { toString(): string; sources: string[] };
type Remapping = (input: unknown, loader: (sourcefile: string) => unknown, options?: boolean) => SourceMapish;
const remapping = remappingImport as unknown as Remapping;

export interface BuildResult {
  written: string[];
  errors: string[];
  /** non-fatal: same-basename .ts + .tsi pairs (spec decision 5) */
  warnings: string[];
}

/** First line of the emitted config bundle; the overwrite guard keys on it. */
const CONFIG_BUNDLE_MARKER = "// generated by nola build — self-configuring Nola config bundle";

export async function cmdBuild(dirArg = ".", outArg = "dist"): Promise<BuildResult> {
  const dir = resolve(dirArg);
  const out = resolve(outArg);
  const sourceRoot = findProjectRoot(dir);
  const { underivableContextType } = await loadCompilerOptions(dir);
  const { target, configPath } = await loadBuildOptions(dir);
  const wireConfig = target === "app" && configPath !== null;
  const configOutPath = join(out, "nola.config.js");
  const written: string[] = [];
  const errors: string[] = [];
  const lowered: LoweredEntry[] = [];

  const { tsi, siblings } = await walkProject(dir);
  const warnings = siblings.map(siblingWarning);

  // App builds ship the config: bundle nola.config.ts (relative imports
  // inlined, packages external) with a self-configuring wrapper, emitted
  // first so a bad config fails the build before any compilation.
  if (wireConfig) {
    if (existsSync(configOutPath) && !(await readFile(configOutPath, "utf8")).startsWith(CONFIG_BUNDLE_MARKER)) {
      errors.push(
        `${configOutPath}: exists and was not generated by nola build — refusing to overwrite. Is another toolchain compiling nola.config.ts into --out?`,
      );
      return { written, errors, warnings };
    }
    try {
      const bundled = await bundleSelfConfiguringConfig(configPath as string);
      await mkdir(out, { recursive: true });
      await writeFile(configOutPath, `${CONFIG_BUNDLE_MARKER}\n${bundled}`);
      written.push(configOutPath);
    } catch (err) {
      errors.push(err instanceof Error ? err.message : String(err));
      return { written, errors, warnings };
    }
  }

  const deriver = createProjectDeriver(dir, sourceRoot, underivableContextType);
  try {
    return await buildWith(deriver);
  } finally {
    deriver.dispose();
  }

  async function buildWith(deriver: ProjectDeriver): Promise<BuildResult> {
  for (const file of tsi) {
    const source = await readFile(file, "utf8");
    // phase 1 + the checker pass (emit 15): the appendix accessors carry real bodies from here on
    const result = deriver.lower(file, source);
    if (result.diagnostics.length > 0) {
      errors.push(printDiagnostics(result.diagnostics, () => source));
      continue;
    }
    lowered.push({ file, loweredCode: result.code });
    errors.push(...danglingViewErrors(file, result.meta.views));

    // The wiring import is appended to the TRANSFORM INPUT only — the
    // declarations pass reuses result.code and must never see it. EOF keeps
    // positions intact; the appended line has no counterpart in result.map,
    // so it stays unmapped after the merge.
    const outPath = `${join(out, relative(dir, file))}.js`;
    let emitCode = result.code;
    if (wireConfig) {
      const rel = relative(dirname(outPath), configOutPath).replace(/\\/g, "/");
      emitCode = `${result.code}\nimport ${JSON.stringify(rel.startsWith(".") ? rel : `./${rel}`)};\n`;
    }
    const js = transformSync(emitCode, { loader: "ts", format: "esm", sourcemap: "external", sourcefile: file });
    let consumed = false;
    const merged = remapping(js.map, () => {
      if (consumed) return null;
      consumed = true;
      return result.map;
    });
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, `${js.code}\n//# sourceMappingURL=${basename(outPath)}.map\n`);
    await writeFile(`${outPath}.map`, merged.toString());
    written.push(outPath, `${outPath}.map`);
  }

  const decl = await emitDeclarationTexts(lowered, sourceRoot, dir, { deriveView: deriver.viewCode });
  for (const [file, declarationText] of decl.tsi) {
    // Next to the built .js in --out (report.tsi.js + report.tsi.d.ts pair
    // under NodeNext), NEVER adjacent to the source: the editor serves
    // .tsi virtually, and an on-disk declaration would only shadow it.
    const dtsPath = `${join(out, relative(dir, file))}.d.ts`;
    await mkdir(dirname(dtsPath), { recursive: true });
    await writeFile(dtsPath, declarationText);
    written.push(dtsPath);
  }
  // Every VIEW the program reached becomes a real `<base>.tsi.js` +
  // `<base>.tsi.d.ts` pair beside the lowered output — the NodeNext pair real
  // .tsi files get — so production output needs no loader at all. The view
  // re-exports `./<base>.js`, so the plain module compiles into the same tree.
  for (const [viewSource, declarationText] of decl.views) {
    const src = resolve(viewSource); // tshost keys views by posix path; `written` stays platform-native
    const base = basename(src).replace(/\.d\.ts$|\.ts$/, "");
    const outDir = join(out, relative(dir, dirname(src)));
    const viewCode = deriver.viewCode(src);
    if (viewCode === undefined) {
      errors.push(`${src}: the view of this module could not be derived (see the diagnostics above)`);
      continue;
    }
    const js = transformSync(viewCode, { loader: "ts", format: "esm" });
    await mkdir(outDir, { recursive: true });
    const jsPath = join(outDir, `${base}.tsi.js`);
    const dtsPath = join(outDir, `${base}.tsi.d.ts`);
    await writeFile(jsPath, js.code);
    await writeFile(dtsPath, declarationText);
    written.push(jsPath, dtsPath);
  }
  return { written, errors, warnings };
  }
}
