import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { cmdBuild, findNolaFiles } from "nola-lang";
import { describe, expect, it } from "vitest";

const ANALYZE_TSI = [
  "export infer function analyze(q: string) {",
  "  const v = ask ..`value`<string>;",
  "  return v;",
  "}",
  "",
].join("\n");

async function makeProject(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), "nola-build-"));
  await mkdir(join(dir, "src", "nested"), { recursive: true });
  await mkdir(join(dir, "node_modules", "junk"), { recursive: true });
  await writeFile(join(dir, "src", "analyze.tsi"), ANALYZE_TSI);
  await writeFile(join(dir, "src", "nested", "extra.tsi"), "export const i = ..`n`<number>;\n");
  await writeFile(join(dir, "node_modules", "junk", "skip.tsi"), "export const i = ..`n`;\n");
  return dir;
}

describe("findNolaFiles", () => {
  it("finds .tsi recursively, skipping node_modules", async () => {
    const dir = await makeProject();
    const files = await findNolaFiles(dir);
    expect(files.some((f) => f.endsWith("analyze.tsi"))).toBe(true);
    expect(files.some((f) => f.endsWith("extra.tsi"))).toBe(true);
    expect(files.some((f) => f.includes("node_modules"))).toBe(false);
  });
});

describe("cmdBuild", () => {
  it("emits js + map + declarations into out/ mirroring structure — never into src", async () => {
    const dir = await makeProject();
    const { written, errors } = await cmdBuild(dir, join(dir, "dist"));
    expect(errors).toEqual([]);

    const jsPath = join(dir, "dist", "src", "analyze.tsi.js");
    expect(existsSync(jsPath)).toBe(true);
    const js = await readFile(jsPath, "utf8");
    expect(js).toContain("await __nola.ask(");
    expect(js).toContain("sourceMappingURL=analyze.tsi.js.map");

    const map = JSON.parse(await readFile(`${jsPath}.map`, "utf8")) as { sources: string[] };
    expect(map.sources.some((s) => s.endsWith("analyze.tsi"))).toBe(true);

    // Declarations pair with the built js in --out (NodeNext: importing
    // "./analyze.tsi.js" finds analyze.tsi.d.ts). The source tree stays clean:
    // the editor serves .tsi virtually and an adjacent file would shadow it.
    const dts = join(dir, "dist", "src", "analyze.tsi.d.ts");
    expect(existsSync(dts)).toBe(true);
    expect(await readFile(dts, "utf8")).toContain("export declare function analyze");
    expect(existsSync(join(dir, "src", "analyze.d.tsi.ts"))).toBe(false);

    expect(existsSync(join(dir, "dist", "src", "nested", "extra.tsi.js"))).toBe(true);
    expect(written.length).toBeGreaterThanOrEqual(4);
  });

  it("reports NOLA diagnostics as errors without writing output for the bad file", async () => {
    const dir = await mkdtemp(join(tmpdir(), "nola-badbuild-"));
    await writeFile(join(dir, "bad.tsi"), "const v = ask ..`v`;\n");
    const { errors } = await cmdBuild(dir, join(dir, "dist"));
    expect(errors.some((e) => e.includes("NOLA2001"))).toBe(true);
    expect(existsSync(join(dir, "dist", "bad.tsi.js"))).toBe(false);
  });
});

const INLINE_PROVIDER = "{ name: 'p', complete: async () => ({ text: '\"x\"' }) }";

async function makeAppProject(): Promise<string> {
  const dir = await makeProject();
  await writeFile(join(dir, "nola.config.ts"), `export default { providers: { default: ${INLINE_PROVIDER} } };\n`);
  return dir;
}

describe("cmdBuild config wiring", () => {
  it("app build emits a self-configuring dist/nola.config.js and per-file appendix imports", async () => {
    const dir = await makeAppProject();
    const { written, errors } = await cmdBuild(dir, join(dir, "dist"));
    expect(errors).toEqual([]);

    const bundlePath = join(dir, "dist", "nola.config.js");
    expect(written).toContain(bundlePath);
    const bundle = await readFile(bundlePath, "utf8");
    expect(bundle).toContain("generated by nola build");
    expect(bundle).toContain("nolaRuntime.configure(");

    const js = await readFile(join(dir, "dist", "src", "analyze.tsi.js"), "utf8");
    expect(js).toContain('import "../nola.config.js"');
    const nested = await readFile(join(dir, "dist", "src", "nested", "extra.tsi.js"), "utf8");
    expect(nested).toContain('import "../../nola.config.js"');

    // Declarations never carry the wiring import.
    const dts = await readFile(join(dir, "dist", "src", "analyze.tsi.d.ts"), "utf8");
    expect(dts).not.toContain("nola.config");
  });

  it("lib build (build.target lib) emits no config artifacts", async () => {
    const dir = await makeProject();
    await writeFile(
      join(dir, "nola.config.ts"),
      `export default { build: { target: 'lib' }, providers: { default: ${INLINE_PROVIDER} } };\n`,
    );
    const { errors } = await cmdBuild(dir, join(dir, "dist"));
    expect(errors).toEqual([]);
    expect(existsSync(join(dir, "dist", "nola.config.js"))).toBe(false);
    const js = await readFile(join(dir, "dist", "src", "analyze.tsi.js"), "utf8");
    expect(js).not.toContain("nola.config.js");
  });

  it("config-less build emits no config artifacts (unchanged behavior)", async () => {
    const dir = await makeProject();
    const { errors } = await cmdBuild(dir, join(dir, "dist"));
    expect(errors).toEqual([]);
    expect(existsSync(join(dir, "dist", "nola.config.js"))).toBe(false);
  });

  it("refuses to overwrite a foreign dist/nola.config.js, but rebuilds over its own", async () => {
    const dir = await makeAppProject();
    await mkdir(join(dir, "dist"), { recursive: true });
    await writeFile(join(dir, "dist", "nola.config.js"), "export default {};\n");
    const refused = await cmdBuild(dir, join(dir, "dist"));
    expect(refused.errors.some((e) => e.includes("refusing to overwrite"))).toBe(true);

    await rm(join(dir, "dist", "nola.config.js"));
    expect((await cmdBuild(dir, join(dir, "dist"))).errors).toEqual([]);
    expect((await cmdBuild(dir, join(dir, "dist"))).errors).toEqual([]);
  });
});
